#!/bin/bash

PIPE0=$(mktemp -u)
mkfifo $PIPE0
exec 3<>$PIPE0
rm $PIPE0

$cis_base_dir/core/startjob maintenance/build_cpp_websrv | head -n 1 | awk -F" " '{ print $4 }' | awk -F"=" '{ print $2 }' >&3 &
pids[0]=$!

PIPE1=$(mktemp -u)
mkfifo $PIPE1
exec 4<>$PIPE1
rm $PIPE1

$cis_base_dir/core/startjob maintenance/build_vuejs_webui | head -n 1 | awk -F" " '{ print $4 }' | awk -F"=" '{ print $2 }' >&4 &
pids[1]=$!


for pid in ${pids[*]}; do
    wait $pid || exit 1
done

#TODO exit if nothing
read build_dir[0] <&3
read build_dir[1] <&4

$cis_base_dir/core/setparam "cpp_build_number" ${build_dir[0]}
$cis_base_dir/core/setparam "vuejs_build_number" ${build_dir[1]}

$cis_base_dir/core/startjob maintenance/deploy
