#!/bin/bash

cd ../cis1-webui-native-srv-cpp || exit 1

git pull origin master || exit 1

mkdir ../build

cd ../build || exit 1

conan install ../cis1-webui-native-srv-cpp || exit 1

cmake ../cis1-webui-native-srv-cpp -DCMAKE_CXX_COMPILER=/usr/bin/g++-8 -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_BUILD_TYPE=Release || exit 1

make -j4 || exit 1

cp bin/ts_ws ../$build_number || exit 1
